spring:
  app:
    name: my-application

  config:
    import: classpath:data-source.yml

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    api-url: http://localhost:8080/api/employees
